# -----------------------------------------------------------------------------
# Automation / AI toolkit – Docker Compose stack
# -----------------------------------------------------------------------------

x-healthcheck: &default-healthcheck
  interval: 30s    # probe every 30 seconds
  timeout: 3s      # mark failure if response >3 s
  retries: 3       # need 3 failures to go unhealthy
  start_period: 10s # grace period after container start

networks:
  internal:
    driver: overlay

volumes:
  n8n_storage:
  qdrant_storage:
  langfuse_storage:
  pgdata_n8n:
  pgdata_langfuse:
  clickhouse_data:

# -----------------------------------------------------------------------------
# Docker Secrets – keep credentials out of the compose file.
# -----------------------------------------------------------------------------
secrets:
  n8n_basic_auth_user:
    external: true
  n8n_basic_auth_password:
    external: true
  n8n_encryption_key:
    external: true
  langfuse_nextauth_secret:
    external: true
  postgres_n8n_password:
    external: true
  postgres_langfuse_password:
    external: true

services:
  # ---------------------------------------------------------------------------
  # Postgres for n8n
  # ---------------------------------------------------------------------------
  postgres_n8n:
    image: postgres:17-alpine3.22
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_n8n_password
      POSTGRES_DB: n8n
    volumes:
      - pgdata_n8n:/var/lib/postgresql/data
    secrets: [postgres_n8n_password]
    networks: [internal]
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    deploy:
      resources:
        limits: {cpus: "1.0", memory: 2g}

  # ---------------------------------------------------------------------------
  # Postgres for Langfuse
  # ---------------------------------------------------------------------------
  postgres_langfuse:
    image: postgres:17-alpine3.22
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_langfuse_password
      POSTGRES_DB: langfuse
    volumes:
      - pgdata_langfuse:/var/lib/postgresql/data
    secrets: [postgres_langfuse_password]
    networks: [internal]
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    deploy:
      resources:
        limits: {cpus: "1.0", memory: 2g}

  # ---------------------------------------------------------------------------
  # n8n – workflow automation
  # ---------------------------------------------------------------------------
  n8n:
    image: n8nio/n8n:1.99.1
    ports: ["5678:5678"]
    
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres_n8n
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER_FILE: /run/secrets/n8n_basic_auth_user
      N8N_BASIC_AUTH_PASSWORD_FILE: /run/secrets/n8n_basic_auth_password
      N8N_ENCRYPTION_KEY_FILE: /run/secrets/n8n_encryption_key
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_METRICS: "false"
      N8N_PERSONALIZATION_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
      N8N_DIAGNOSTICS_ENABLED: "false"
      GENERIC_TIMEZONE: UTC
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      - postgres_n8n
      - qdrant
    secrets:
      - n8n_basic_auth_user
      - n8n_basic_auth_password
      - n8n_encryption_key
      - postgres_n8n_password
    extra_hosts:
      - "host.docker.internal:host-gateway"  # reach host‑side Ollama
    entrypoint: >
      sh -c '
        export DB_POSTGRESDB_PASSWORD="$$(cat /run/secrets/postgres_n8n_password)" &&
        exec tini -- n8n'
    networks: [internal]
    deploy:
      resources:
        limits: {cpus: "1.0", memory: 1g}

  # ---------------------------------------------------------------------------
  # Qdrant – vector database
  # ---------------------------------------------------------------------------
  qdrant:
    image: qdrant/qdrant:v1.14.1
    ports: ["6333:6333"]
    volumes:
      - qdrant_storage:/qdrant/storage
    networks: [internal]
    deploy:
      resources:
        limits: {cpus: "2.0", memory: 4g}


  # ---------------------------------------------------------------------------
  # Prometheus – metrics scraper
  # ---------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v3.4.1
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [internal]
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
    deploy:
      resources:
        limits: {cpus: "1.0", memory: 1g}

  # ---------------------------------------------------------------------------
  # ClickHouse – for Langfuse analytics
  # ---------------------------------------------------------------------------
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    environment:
      CLICKHOUSE_DB: langfuse
      CLICKHOUSE_USER: langfuse
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: langfuse_clickhouse_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks: [internal]
    deploy:
      resources:
        limits: {cpus: "1.0", memory: 2g}

  # ---------------------------------------------------------------------------
  # Langfuse – LLM observability
  # ---------------------------------------------------------------------------
  langfuse:
    image: langfuse/langfuse:3.73.1
    ports: ["3000:3000"]
    environment:
      NEXTAUTH_SECRET_FILE: /run/secrets/langfuse_nextauth_secret
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: production
      CLICKHOUSE_URL: clickhouse://langfuse:langfuse_clickhouse_password@clickhouse:8123/langfuse
      LANGFUSE_DEFAULT_PROJECT_ROLE: "ADMIN"
      LANGFUSE_DEFAULT_PROJECT_ID: "default"
    volumes:
      - langfuse_storage:/data
    secrets:
      - langfuse_nextauth_secret
      - postgres_langfuse_password
    depends_on:
      - postgres_langfuse
      - clickhouse
    extra_hosts:
      - "host.docker.internal:host-gateway"  # reach host‑side Ollama
    entrypoint: >
      sh -c '
        PASSWORD=$$(cat /run/secrets/postgres_langfuse_password) &&
        export DATABASE_URL="postgres://langfuse:$$PASSWORD@postgres_langfuse:5432/langfuse" &&
        echo "DATABASE_URL set successfully" &&
        exec dumb-init -- ./web/entrypoint.sh'
    networks: [internal]
    deploy:
      resources:
        limits: {cpus: "1.0", memory: 2g}
