[tasks."bootstrap:secrets"]
description = "Bootstrap secrets for the AI Toolkit using 1Password CLI."
run = """
  op read op://ai-toolkit/n8n_basic_auth_password/password | docker secret create n8n_basic_auth_password -
  op read op://ai-toolkit/n8n_encryption_key/password | docker secret create n8n_encryption_key -
  op read op://ai-toolkit/langfuse_nextauth_secret/password | docker secret create langfuse_nextauth_secret -
  op read op://ai-toolkit/postgres_n8n_password/password | docker secret create postgres_n8n_password -
  op read op://ai-toolkit/postgres_langfuse_password/password | docker secret create postgres_langfuse_password -
  op read op://ai-toolkit/clickhouse_password/password | docker secret create clickhouse_password -
  op read op://ai-toolkit/langfuse_salt/password | docker secret create langfuse_salt -
"""

[tasks."bootstrap:docker:swarm"]
description = "Bootstrap Docker Swarm for the AI Toolkit."
run = "docker swarm init"

[tasks."bootstrap:docker:deploy"]
description = "Deploy the AI Toolkit stack to Docker Swarm."
run = "docker stack deploy -c docker-compose.yml ai_toolkit --detach"
alias = "deploy"
wait_for = "docker:swarm:remove"

[tasks."docker:swarm:remove"]
description = "Nuke the AI Toolkit environment. (Minus volumes)"
run = "docker stack rm ai_toolkit"
alias = "down"

[tasks."docker:prune"]
description = "Prune unused Docker resources (containers, networks, images)"
run = "docker system prune -f"
alias = "prune"

[tasks."bounce"]
description = "Bounce the AI Toolkit stack."
depends = ["docker:swarm:remove"]
run = "./scripts/check-removing.sh"
depends_post = ["bootstrap:docker:deploy"]

[tools]
1password-cli = "latest"
